age=int(input("What is your age "))
birthplace=input("Where were you born? ")
name=input("What is your name? ")
mom=input("What is your mom's name? ")
dad=input("what is your dad's name? ")
study=input("What was your major? ")
haircolor=input("What is your hair color? ")
college=input("What college did you attend? ")
print(f"So {name}, your a disappointment to your parents. Your {age} living with your parents ({mom} and {dad}) and of course still in your hometown of {birthplace}. You couldn't make it through your career as a {study} major because you gave up in order to live your dream as a dumb {haircolor} shmuck who lives off of {mom} and {dad} income. Oh and of course you decided to flunk out of {college} on the first day because you heard of the midterms.")